<a href="https://colab.research.google.com/github/pirsquared/Advent-of-Code/blob/master/2018/Day11_improved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Faster
`numba` isn't necessary but does help

In [1]:
!pip install numba

In [0]:
import pandas as pd
import numpy as np

from numba import njit

In [0]:
 def get_a(data):
    d = int(data)
    j = np.arange(1, 301)
    i = np.arange(1, 301)
    r = j + 10
    p = (r * i[:, None] + d) * r // 100 % 10 - 5
    return p

In [4]:
@njit
def f(c):
  n = c.shape[0]
  n = n - 1
  maxpower = np.array([0, 0, 0, 0])
  
  for i in range(n):
    for j in range(n):
      for k in range(n - max(i, j)):
        power = g(c, i, j, k)
        if power > maxpower[-1]:
          maxpower[:] = [j + 1, i + 1, k, power]
          
  return maxpower
        
@njit
def g(a, i, j, k):
  return a[i+k, j+k] - a[i, j+k] - a[i+k, j] + a[i, j]
        

array([ 90, 269,  16, 113])

# Deal Maker
By calculating the 2-D cumulative sumation, I've pre-calculated much of what will be needed to determine the convolutions.  I'll will have reduced every sum over a kernel to an operation over four numbers.

In [0]:
def pad(a):
  n, m = a.shape
  c = np.zeros((n + 1, m + 1), a.dtype)
  c[1:, 1:] = a.cumsum(0).cumsum(1)
  
  return c

In [5]:
f(pad(get_a(18)))

array([ 90, 269,  16, 113])

In [6]:
f(pad(get_a(42)))

array([232, 251,  12, 119])

In [7]:
f(pad(get_a(5177)))

array([231, 135,   8,  80])

In [8]:
%timeit f(pad(get_a(5177)))

100 loops, best of 3: 18.4 ms per loop
